### ISSUE TITLE
插件名命名规则建议更改为 Kebab Case

### ISSUE THREAD

**Issue by JohnNiang** [chengzhongxue/plugin-friends-old#1]
例如：PluginFriends -> plugin-friends，可能需要全局搜索同步修改其他地方。

> https://github.com/chengzhongxue/plugin-friends/blob/3c4a59ffd6b3786bf545b495309460026897329f/src/main/resources/plugin.yaml#L4

**Comment by chengzhongxue** [comment]
已修改

**Comment by chengzhongxue** [comment]
> 例如：PluginFriends -> plugin-friends，可能需要全局搜索同步修改其他地方。
> 
> > https://github.com/chengzhongxue/plugin-friends/blob/3c4a59ffd6b3786bf545b495309460026897329f/src/main/resources/plugin.yaml#L4

已修改
