### ISSUE TITLE
朋友圈定时任务不生效

### ISSUE THREAD

**Issue by 52lemon6** [chengzhongxue/plugin-friends-old#16]
朋友圈定时任务不生效，表达式设置了每日零点，但是最近更新都是在两天前
![image](https://github.com/chengzhongxue/plugin-friends/assets/40059643/dfb1699b-a804-4f01-9763-30e97cf57b36)
![image](https://github.com/chengzhongxue/plugin-friends/assets/40059643/38937c33-f0b2-442d-88bf-c369a5666ca5)

**Comment by chengzhongxue** [comment]
> 朋友圈定时任务不生效，表达式设置了每日零点，但是最近更新都是在两天前 ![image](https://private-user-images.githubusercontent.com/40059643/324676880-dfb1699b-a804-4f01-9763-30e97cf57b36.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NDMzNzAsIm5iZiI6MTcxMzg0MzA3MCwicGF0aCI6Ii80MDA1OTY0My8zMjQ2NzY4ODAtZGZiMTY5OWItYTgwNC00ZjAxLTk3NjMtMzBlOTdjZjU3YjM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDAzMzExMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyMzJiZTAxOGQxMzM1MDZmZDc5MTIwN2YzMTZiMTJiYTQ2MWE0MDQ4YTQwY2QwYTllMmRkZmUzYzk3OTY0NmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bNfZ10E-a8GEbZ8HUbciBdpxEi6PJT3haBK63Z7g6gQ) ![image](https://private-user-images.githubusercontent.com/40059643/324677011-38937c33-f0b2-442d-88bf-c369a5666ca5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NDMzNzAsIm5iZiI6MTcxMzg0MzA3MCwicGF0aCI6Ii80MDA1OTY0My8zMjQ2NzcwMTEtMzg5MzdjMzMtZjBiMi00NDJkLTg4YmYtYzM2OWE1NjY2Y2E1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDAzMzExMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzOWUwMDgwMTFkOWVmOTQ0MTE2OTVmNTFiNzhkYjU1NzBiMjIyNDQ3NGQ5MjZhYTBiNmViMDM3MzU5NzE2YWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MSCGHTHbwzWF8ydyUdwI6StJ0qgrUVezryVGjsfx_Eg)

![image](https://github.com/chengzhongxue/plugin-friends/assets/89380218/8df974c4-dec1-4f6a-8f45-274bb4518514)
这个不是？你其他的没有更新的他更新什么呢
