### ISSUE TITLE
请问1.3.5版本是会自动通过/links中的链接自动获取朋友圈订阅地址吗？

### ISSUE THREAD

**Issue by wuba-pat** [chengzhongxue/plugin-friends-old#19]
然后还有个问题，进入/friends 页面后，点击文章的标题不能实现跳转。

https://funnywii.com/friends

比如在我的这个页面，点击文章标题后会返回当前页，而不是进入标题对应的blog

**Comment by chengzhongxue** [comment]
下个版本解决这个问题

**Comment by chengzhongxue** [comment]
你安装了1.3.4之前的版本你没按照文档进行操作， 因为插件重构了

**Comment by wuba-pat** [comment]
> 你安装了1.3.4之前的版本你没按照文档进行操作， 因为插件重构了

这个有啥补救办法吗？我把之前版本的朋友圈整个插件都卸载了，配置文件也删除了。

**Comment by chengzhongxue** [comment]
> > 你安装了1.3.4之前的版本你没按照文档进行操作， 因为插件重构了
> 
> 这个有啥补救办法吗？我把之前版本的朋友圈整个插件都卸载了，配置文件也删除了。

文档里有说清掉哪些东西， 你之前的数据没删掉，这是你之前的数据导致的

**Comment by chengzhongxue** [comment]
![image](https://github.com/user-attachments/assets/bfc4395c-c8bb-4ab3-8417-2cc5f5ee103b)

**Comment by FunnyWii** [comment]
我目前的步骤是
1. 卸载现有1.3.5版本的朋友圈插件并清空配置
2. Data Studio中删除CronFriendPost对应项
3. 重新安装1.3.5版本朋友圈插件

请问这个流程对吗？
如果对的话，那还是存在我说的那个问题...

**Comment by wuba-pat** [comment]
> 我目前的步骤是
> 
> 1. Halo Console中卸载现有1.3.5版本的朋友圈插件并清空配置
> 2. Data Studio中删除CronFriendPost对应项
> 3. Console插件市场重新安装1.3.5版本朋友圈插件
> 
> 请问这个流程对吗？ 如果对的话，那还是存在我说的那个问题...

**Comment by chengzhongxue** [comment]
你的订阅数据没删掉，删插件那个数据是不会给你删掉的，要自己去那个页面删

**Comment by wuba-pat** [comment]
> 你的订阅数据没删掉，删插件那个数据是不会给你删掉的，要自己去那个页面删

是的丫，最开始确实没删掉。


> > 我目前的步骤是
> > 
> > 1. Halo Console中卸载现有1.3.5版本的朋友圈插件并清空配置
> > 2. Data Studio中删除CronFriendPost对应项
> > 3. Console插件市场重新安装1.3.5版本朋友圈插件
> > 
> > 请问这个流程对吗？ 如果对的话，那还是存在我说的那个问题...

所以后来是按照这个流程走了一遍，第二步是按照您发的截图来操作的，莫非这样也不对吗...

**Comment by chengzhongxue** [comment]
你截图看订阅数据的地方

**Comment by chengzhongxue** [comment]
![image](https://github.com/user-attachments/assets/dacad7e3-1f95-4ec3-8b49-3617023fcf04)
我表达有问题？

**Comment by wuba-pat** [comment]
> ![image](https://private-user-images.githubusercontent.com/89380218/371837026-dacad7e3-1f95-4ec3-8b49-3617023fcf04.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1OTc0MDcsIm5iZiI6MTcyNzU5NzEwNywicGF0aCI6Ii84OTM4MDIxOC8zNzE4MzcwMjYtZGFjYWQ3ZTMtMWY5NS00ZWMzLThiNDktMzYxNzAyM2ZjZjA0LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyOVQwODA1MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNGY0ZWYyYjEwOTYzMDFkZDI0NzI2YTQ3ZTlkZWYxYjExOGFmYzI3OGI1OGM1OGI2MzY0MzllMjJmODJhMTk3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.DJlNbGSBubQ2D4Ag01R72rNEUVtFGeZ9iOwZajnlWqE) 我表达有问题？

没有问题了那...后台各个插件用的不太熟...

**Comment by chengzhongxue** [comment]
算了，我还是去补两张图吧，我感觉还是有人会碰到这个问题

**Comment by wuba-pat** [comment]
> 算了，我还是去补两张图吧，我感觉还是有人会碰到这个问题

感谢作者，最后请教个问题，朋友圈获取订阅的方式是自动从友链插件里的链接去拉取对吗？
也就是和以前需要手动添加RSS订阅的方式不同了？

**Comment by chengzhongxue** [comment]
是的

**Comment by wuba-pat** [comment]
谢谢。没有问题了
