### ISSUE TITLE
同步的时候遇到几个错误

### ISSUE THREAD

**Issue by ZenCoderWu** [chengzhongxue/plugin-friends-old#5]
![image](https://github.com/chengzhongxue/plugin-friends/assets/24646311/b7d50d4a-8fb3-4e81-a9a2-d10c7da0b30f)
![image](https://github.com/chengzhongxue/plugin-friends/assets/24646311/9e6e9351-2e92-41c3-9a7d-d12eb5dea751)

**Comment by chengzhongxue** [comment]
你上面的订阅链接能访问？

**Comment by ZenCoderWu** [comment]
> 你上面的订阅链接能访问？

Invalid Date
https://rsshub.app/oschina/news/project 
https://rsshub.app/weixin/miniprogram/devtools
*** 
NPE
https://rsshub.app/mi/golden 
https://rsshub.app/sec-wiki/weekly 
https://rsshub.app/bilibili/hot-search 
https://rsshub.app/blogread/newest

**Comment by chengzhongxue** [comment]
> > 你上面的订阅链接能访问？
> 
> Invalid Date https://rsshub.app/oschina/news/project https://rsshub.app/weixin/miniprogram/devtools
> 
> NPE https://rsshub.app/mi/golden https://rsshub.app/sec-wiki/weekly https://rsshub.app/bilibili/hot-search https://rsshub.app/blogread/newest

你这几个链接我都访问不了，怎么拉取

**Comment by ZenCoderWu** [comment]
> > > 你上面的订阅链接能访问？
> > 
> > 
> > Invalid Date https://rsshub.app/oschina/news/project https://rsshub.app/weixin/miniprogram/devtools
> > NPE https://rsshub.app/mi/golden https://rsshub.app/sec-wiki/weekly https://rsshub.app/bilibili/hot-search https://rsshub.app/blogread/newest
> 
> 你这几个链接我都访问不了，怎么拉取

哦 我知道了 可能是墙的问题
