### ISSUE TITLE
Failed to fetch friends

### ISSUE THREAD

**Issue by nukix** [chengzhongxue/plugin-friends-old#8]
在"RSS 订阅"->"订阅文章"会请求 "/apis/api.plugin.halo.run/v1alpha1/plugins/plugin-friends/friendposts?page=1&size=20&keyword=" 接口。

可能由于数据量比较大， 请求时间超过一秒就会报错， 
bundle.js?t=1708448462696:1682 Failed to fetch friends 
 {message: 'timeout of 1000ms exceeded', name: 'AxiosError', code: 'ECONNABORTED'

第一次请求后， 后面会重试三次， 但由于 timeout 是 1000ms， 所以都请求失败， 导致列表加载不出来。

**Comment by chengzhongxue** [comment]
> 在"RSS 订阅"->"订阅文章"会请求 "/apis/api.plugin.halo.run/v1alpha1/plugins/plugin-friends/friendposts?page=1&size=20&keyword=" 接口。
> 
> 可能由于数据量比较大， 请求时间超过一秒就会报错， bundle.js?t=1708448462696:1682 Failed to fetch friends  {message: 'timeout of 1000ms exceeded', name: 'AxiosError', code: 'ECONNABORTED'
> 
> 第一次请求后， 后面会重试三次， 但由于 timeout 是 1000ms， 所以都请求失败， 导致列表加载不出来。

[plugin-friends-1.2.1-test.jar.zip](https://github.com/chengzhongxue/plugin-friends/files/14357625/plugin-friends-1.2.1-test.jar.zip)

你试一下这个包

**Comment by nukix** [comment]
> > 在"RSS 订阅"->"订阅文章"会请求 "/apis/api.plugin.halo.run/v1alpha1/plugins/plugin-friends/friendposts?page=1&size=20&keyword=" 接口。
> > 可能由于数据量比较大， 请求时间超过一秒就会报错， bundle.js?t=1708448462696:1682 Failed to fetch friends  {message: 'timeout of 1000ms exceeded', name: 'AxiosError', code: 'ECONNABORTED'
> > 第一次请求后， 后面会重试三次， 但由于 timeout 是 1000ms， 所以都请求失败， 导致列表加载不出来。
> 
> [plugin-friends-1.2.1-test.jar.zip](https://github.com/chengzhongxue/plugin-friends/files/14357625/plugin-friends-1.2.1-test.jar.zip)
> 
> 你试一下这个包

刚试了一下， 这一个可以正常读出来， 谢谢！ 😄

**Comment by chengzhongxue** [comment]
> > > 在"RSS 订阅"->"订阅文章"会请求 "/apis/api.plugin.halo.run/v1alpha1/plugins/plugin-friends/friendposts?page=1&size=20&keyword=" 接口。
> > > 可能由于数据量比较大， 请求时间超过一秒就会报错， bundle.js?t=1708448462696:1682 Failed to fetch friends  {message: 'timeout of 1000ms exceeded', name: 'AxiosError', code: 'ECONNABORTED'
> > > 第一次请求后， 后面会重试三次， 但由于 timeout 是 1000ms， 所以都请求失败， 导致列表加载不出来。
> > 
> > 
> > [plugin-friends-1.2.1-test.jar.zip](https://github.com/chengzhongxue/plugin-friends/files/14357625/plugin-friends-1.2.1-test.jar.zip)
> > 你试一下这个包
> 
> 刚试了一下， 这一个可以正常读出来， 谢谢！ 😄

下个版本更新
