### ISSUE TITLE
[feat] 请问是否考虑朋友圈页面增加返回博客首页的功能

### ISSUE THREAD

**Issue by leeyin98** [chengzhongxue/plugin-friends-old#9]
如果页面设置时不使用新页签打开而是当前页面打开的话，无法通过页面操作返回博客首页（即使设置了新页签打开有时也会在当前页打开，这可能是Halo的Bug），得在地址栏删除上下文打开博客首页。

**Comment by QwindF** [comment]
可以参考这种嵌套页面的方式来达到目的
https://blog.qwind.fun/yl

**Comment by leeyin98** [comment]
> 可以参考这种嵌套页面的方式来达到目的 https://blog.qwind.fun/yl

谢谢，这确实也是一种方法。
但感觉多数人应该还是以独立页面来显示的。（进朋友圈一直找不到出口，心里像是有蚂蚁在爬哈哈哈：）

**Comment by chengzhongxue** [comment]
插件配置添加了
![image](https://github.com/chengzhongxue/plugin-friends/assets/89380218/7e158037-80e4-4669-81b0-ce4e1c8f35e1)
